### ISSUE TITLE
[chore] Swagger 의존성 추가, .gitignore 파일 추가

### ISSUE THREAD

**Issue by younghyun-j** [HomeChefHub/refooding-be#1]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
API 문서화를 위한 Swagger Springdoc 라이브러리 추가
.gitignore 파일 추가

## ✅ TODO
- [x] Swagger Springdoc 추가
- [x] .gitignore 파일 추가

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.

**Comment by taeyoon-cloud** [comment]
영현님, 혹시 swagger 기본 화면도 잘 나오시나요?
제가 영현님이 올려주신 설정으로 서버 올려서 swagger 문서 확인해보면 white label error가 나오는데 

build.gradle에서 

`implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.7.0'`
이 부분을 

`implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'`

이렇게 바꾼 후에 swagger 문서를 확인하면 스크린샷 처럼 잘 나와서요! 한번 확인 부탁드립니다!


	
![스크린샷 2024-07-15 오후 1 20 12](https://github.com/user-attachments/assets/06513185-1556-4ccc-89f6-b3417a4c02d3)

**Comment by younghyun-j** [comment]
> 영현님, 혹시 swagger 기본 화면도 잘 나오시나요? 제가 영현님이 올려주신 설정으로 서버 올려서 swagger 문서 확인해보면 white label error가 나오는데
> 
> build.gradle에서
> 
> `implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.7.0'` 이 부분을
> 
> `implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'`
> 
> 이렇게 바꾼 후에 swagger 문서를 확인하면 스크린샷 처럼 잘 나와서요! 한번 확인 부탁드립니다!
> 
> ![스크린샷 2024-07-15 오후 1 20 12](https://private-user-images.githubusercontent.com/76869820/348598391-06513185-1556-4ccc-89f6-b3417a4c02d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjA3NDgsIm5iZiI6MTcyMTAyMDQ0OCwicGF0aCI6Ii83Njg2OTgyMC8zNDg1OTgzOTEtMDY1MTMxODUtMTU1Ni00Y2NjLTg5ZjYtYjM0MTdhNGMwMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA1MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTZiZDdmY2MyZDE0ZDk4YjZhYTBmNTBkNzA0NzBmOWJiZmNjNjI0MmJmMmU1YWQyYjY1MWQwM2ZhZWYzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_htf545ZEsoQgk00QfLJCroMEszvbbiv1CePMVMfUE)

<img width="902" alt="image" src="https://github.com/user-attachments/assets/a5f61dea-26ae-422e-b6fe-b23d8e05f68d">

 'implementation 'org.springdoc:springdoc-openapi-ui:1.7.0' 이걸로 했어야했는데 제가 의존성 추가를 그룹으로 잘못한 것 같아요!

- SpringDoc OpenAPI UI
<img width="907" alt="image" src="https://github.com/user-attachments/assets/d2f6f7a7-85bb-48d8-a69e-7a9f458148d9">

- SpringDoc OpenAPI Starter WebMVC UI
<img width="903" alt="image" src="https://github.com/user-attachments/assets/e125e7d4-40fe-4e63-a909-44baa4a174a0">

태윤님이 알려준 버전으로 수정해서 main 브랜치에 merge할게요. 감사합니다!
